"""create user

Revision ID: 36bc2f711a56
Revises:
Create Date: 2022-08-23 18:43:38.598788

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "36bc2f711a56"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_model",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=32), nullable=True),
        sa.Column("hashed_password", sa.String(length=64), nullable=True),
        sa.Column("password_salt", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=32), nullable=True),
        sa.Column("surname", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=64), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_model_email"), "user_model", ["email"], unique=False)
    op.create_index(op.f("ix_user_model_id"), "user_model", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_model_id"), table_name="user_model")
    op.drop_index(op.f("ix_user_model_email"), table_name="user_model")
    op.drop_table("user_model")
    # ### end Alembic commands ###
